sudo: required

services:
- docker

language: java
dist: trusty

jdk:
- openjdk11

cache:
  directories:
  - $HOME/.m2

env:
- DOCKER_IMAGE=40850473/service-users:0.0.2

script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .

after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_IMAGE"
