kumuluzee:
  name: users
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
  - jndi-name: jdbc/UsersDS
    connection-url: jdbc:postgresql://192.168.99.100:5432/user
    username: postgres
    password: postgres
    max-pool-size: 20